[package]
name = "pomodoro"
version = "0.1.0"
description = "Pomodoro Tauri frontend"
edition = "2021"

[build-dependencies]
tauri-build = { version = "1.5", features = [] }

[dependencies]
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
tauri = { version = "1.5", features = [ "shell-all", "system-tray" ] }

[features]
custom-protocol = ["tauri/custom-protocol"]
